* Quadrantids Meteor Shower
   <2019-01-03 Thu>
January 3, 4 
The Quadrantids is an above average shower, with up to 40 meteors per hour at its peak. It is thought to be produced by dust grains left behind by an extinct comet known as 2003 EH1, which was discovered in 2003. The shower runs annually from January 1-5. It peaks this year on the night of the 3rd and  morning of the 4th.  The moon will be a thin crescent and should not interfere with what could be a good show this year. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Bootes, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2019-01-06 Sun 01:28>
January 6 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 01:28 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Venus at Greatest Western Elongation
   <2019-01-06 Sun>
January 6 
The planet Venus reaches greatest eastern elongation of 47 degrees from the Sun. This is the best time to view Venus since it will be at its highest point above the horizon in the morning sky. Look for the bright planet in the eastern sky before sunrise.
(copyright: seasky.org)
* Partial Solar Eclipse
   <2019-01-06 Sun>
January 6 
A partial solar eclipse occurs when the Moon covers only a part of the Sun, sometimes resembling a bite taken out of a cookie. A partial solar eclipse can only be safely observed with a special solar filter or by looking at the Sun's reflection. The partial eclipse will be visible in parts of eastern Asia and the northern Pacific Ocean. It will be best seen from northeastern Russia with 62% coverage.
        (NASA Map and Eclipse Information)
(copyright: seasky.org)
* Full Moon, Supermoon
   <2019-01-21 Mon 05:16>
January 21 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 05:16 UTC. This full moon was known by early Native American tribes as the Full Wolf Moon because this was the time of year when hungry wolf packs howled outside their camps. This moon has also been know as the Old Moon and the Moon After Yule. This is also the first of three supermoons for 2019. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* Conjunction of Venus and Jupiter
   <2019-01-22 Tue>
January 22 
A conjunction of Venus and Jupiter will be visible on January 22. The two bright planets will be visible within 2.4 degrees of each other in the early morning sky. Look for this impressive sight in the east just before sunrise.
(copyright: seasky.org)
* Total Lunar Eclipse
   <2019-01-20 Sun>
January 20 & 21 
A total lunar eclipse occurs when the Moon passes completely through the Earth's dark shadow, or umbra. During this type of eclipse, the Moon will gradually get darker and then take on a rusty or blood red color. The eclipse will be visible throughout most of North America, South America, the eastern Pacific Ocean, western Atlantic Ocean, extreme western Europe, and extreme western Africa.
        (NASA Map and Eclipse Information)
(copyright: seasky.org)
* New Moon
   <2019-02-04 Mon 21:03>
February 4 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 21:03 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2019-02-19 Tue 15:53>
February 19 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 15:53 UTC. This full moon was known by early Native American tribes as the Full Snow Moon because the heaviest snows usually fell during this time of the year. Since hunting is difficult, this moon has also been known by some tribes as the Full Hunger Moon, since the harsh weather made hunting difficult. This is also the second of three supermoons for 2019. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2019-02-27 Wed>
February 27 
The planet Mercury reaches greatest eastern elongation of 18.1 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* New Moon
   <2019-03-06 Wed 16:04>
March 6 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 16:04 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* March Equinox
   <2019-03-20 Wed 21:58>
March 20 
The March equinox occurs at 21:58 UTC. The Sun will shine directly on the equator and there will be nearly equal amounts of day and night throughout the world. This is also the first day of spring (vernal equinox) in the Northern Hemisphere and the first day of fall (autumnal equinox) in the Southern Hemisphere.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2019-03-21 Thu 01:43>
March 21 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 01:43 UTC. This full moon was known by early Native American tribes as the Full Worm Moon because this was the time of year when the ground would begin to soften and the earthworms would reappear. This moon has also been known as the Full Crow Moon, the Full Crust Moon, the Full Sap Moon, and the Lenten Moon. This is also the last of three supermoons for 2019. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* New Moon
   <2019-04-05 Fri 08:51>
April 5 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 08:51 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2019-04-11 Thu>
April 11 
The planet Mercury reaches greatest western elongation of 27.7 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* Full Moon
   <2019-04-19 Fri 11:12>
April 19 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 11:12 UTC. This full moon was known by early Native American tribes as the Full Pink Moon because it marked the appearance of the moss pink, or wild ground phlox, which is one of the first spring flowers. This moon has also been known as the Sprouting Grass Moon, the Growing Moon, and the Egg Moon. Many coastal tribes called it the Full Fish Moon because this was the time that the shad swam upstream to spawn.
(copyright: seasky.org)
* Lyrids Meteor Shower
   <2019-04-22 Mon>
April 22, 23 
The Lyrids is an average shower, usually producing about 20 meteors per hour at its peak. It is produced by dust particles left behind by comet C/1861 G1 Thatcher, which was discovered in 1861. The shower runs annually from April 16-25. It peaks this year on the night of the night of the 22nd and morning of the 23rd. These meteors can sometimes produce bright dust trails that last for several seconds.  The waning gibbous moon will block out many of the fainter meteors this year, but if you are patient you should still be able to catch a few of the brightest ones. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Lyra, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2019-05-04 Sat 22:46>
May 4 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 22:46 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Eta Aquarids Meteor Shower
   <2019-05-06 Mon>
May 6, 7 
The Eta Aquarids is an above average shower, capable of producing up to 60 meteors per hour at its peak. Most of the activity is seen in the Southern Hemisphere. In the Northern Hemisphere, the rate can reach about 30 meteors per hour. It is produced by dust particles left behind by comet Halley, which has known and observed since ancient times. The shower runs annually from April 19 to May 28. It peaks this year on the night of May 6 and the morning of the May 7. The thin crescent moon will set early in the evening leaving dark skies for what should be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Aquarius, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon, Blue Moon
   <2019-05-18 Sat 21:11>
May 18 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 21:11 UTC. This full moon was known by early Native American tribes as the Full Flower Moon because this was the time of year when spring flowers appeared in abundance. This moon has also been known as the Full Corn Planting Moon and the Milk Moon. Since this is the third of four full moons in this season, it is known as a blue moon. This rare calendar event only happens once every few years, giving rise to the term, “once in a blue moon.” There are normally only three full moons in each season of the year. But since full moons occur every 29.53 days, occasionally a season will contain 4 full moons. The extra full moon of the season is known as a blue moon. Blue moons occur on average once every 2.7 years.
(copyright: seasky.org)
* New Moon
   <2019-06-03 Mon 10:02>
June 3 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 10:02 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Jupiter at Opposition
   <2019-06-10 Mon>
June 10 
The giant planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Jupiter and its moons. A medium-sized telescope should be able to show you some of the details in Jupiter's cloud bands. A good pair of binoculars should allow you to see Jupiter's four largest moons, appearing as bright dots on either side of the planet. 
(copyright: seasky.org)
* Full Moon
   <2019-06-17 Mon 08:31>
June 17 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 08:31 UTC. This full moon was known by early Native American tribes as the Full Strawberry Moon because it signaled the time of year to gather ripening fruit. It also coincides with the peak of the strawberry harvesting season. This moon has also been known as the Full Rose Moon and the Full Honey Moon.
(copyright: seasky.org)
* June Solstice
   <2019-06-21 Fri 15:54>
June 21 
The June solstice occurs at 15:54 UTC. The North Pole of the earth will be tilted toward the Sun, which will have reached its northernmost position in the sky and will be directly over the Tropic of Cancer at 23.44 degrees north latitude. This is the first day of summer (summer solstice) in the Northern Hemisphere and the first day of winter (winter solstice) in the Southern Hemisphere.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2019-06-23 Sun>
June 23 
The planet Mercury reaches greatest eastern elongation of 25.2 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* New Moon
   <2019-07-02 Tue 19:16>
July 2 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 19:16 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Total Solar Eclipse
   <2019-07-02 Tue>
July 2 
A total solar eclipse occurs when the moon completely blocks the Sun, revealing the Sun's beautiful outer atmosphere known as the corona. The path of totality will only be visible in parts of the southern pacific Ocean, central Chile, and central Argentina. A partial eclipse will be visible in most parts of the southern Pacific Ocean and western South America. (NASA Map and Eclipse Information)
        (NASA Interactive Google Map)
(copyright: seasky.org)
* Saturn at Opposition
   <2019-07-09 Tue>
July 9 
The ringed planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Saturn and its moons. A medium-sized or larger telescope will allow you to see Saturn's rings and a few of its brightest moons.
(copyright: seasky.org)
* Full Moon
   <2019-07-16 Tue 21:38>
July 16 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 21:38 UTC. This full moon was known by early Native American tribes as the Full Buck Moon because the male buck deer would begin to grow their new antlers at this time of year. This moon has also been known as the Full Thunder Moon and the Full Hay Moon.
(copyright: seasky.org)
* Partial Lunar Eclipse
   <2019-07-16 Tue>
July 16 
A partial lunar eclipse occurs when the Moon passes through the Earth's partial shadow, or penumbra, and only a portion of it passes through the darkest shadow, or umbra. During this type of eclipse a part of the Moon will darken as it moves through the Earth's shadow. The eclipse will be visible throughout most of Europe, Africa, central Asia, and the Indian Ocean. (NASA Map and Eclipse Information)
(copyright: seasky.org)
* Delta Aquarids Meteor Shower
   <2019-07-28 Sun>
July 28, 29 
The Delta Aquarids is an average shower that can produce up to 20 meteors per hour at its peak. It is produced by debris left behind by comets Marsden and Kracht. The shower runs annually from July 12 to August 23. It peaks this year on the night of July 28 and morning of July 29. The waning crescent moon will not be too much of a problem this year. The skies should be dark enough for what could be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Aquarius, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2019-08-01 Thu 03:12>
August 1 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 03:12 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2019-08-09 Fri>
August 9 
The planet Mercury reaches greatest western elongation of 19.0 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* Perseids Meteor Shower
   <2019-08-12 Mon>
August 12, 13 
The Perseids is one of the best meteor showers to observe, producing up to 60 meteors per hour at its peak. It is produced by comet Swift-Tuttle, which was discovered in 1862. The Perseids are famous for producing a large number of bright meteors. The shower runs annually from July 17 to August 24. It peaks this year on the night of August 12 and the morning of August 13. The nearly full moon will block out most of the fainter meteors this year, but the Perseids are so bright and numerous that it could still be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Perseus, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon
   <2019-08-15 Thu 12:30>
August 15 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 12:30 UTC. This full moon was known by early Native American tribes as the Full Sturgeon Moon because the large sturgeon fish of the Great Lakes and other major lakes were more easily caught at this time of year. This moon has also been known as the Green Corn Moon and the Grain Moon.
(copyright: seasky.org)
* New Moon
   <2019-08-30 Fri 10:37>
August 30 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 10:37 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Neptune at Opposition
   <2019-09-09 Mon>
September 9 
The blue giant planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Neptune. Due to its extreme distance from Earth, it will only appear as a tiny blue dot in all but the most powerful telescopes.
(copyright: seasky.org)
* Full Moon
   <2019-09-14 Sat 04:34>
September 14 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 04:34 UTC. This full moon was known by early Native American tribes as the Full Corn Moon because the corn is harvested around this time of year. This moon is also known as the Harvest Moon. The Harvest Moon is the full moon that occurs closest to the September equinox each year.
(copyright: seasky.org)
* September Equinox
   <2019-09-23 Mon 07:50>
September 23 
The September equinox occurs at 07:50 UTC. The Sun will shine directly on the equator and there will be nearly equal amounts of day and night throughout the world. This is also the first day of fall (autumnal equinox) in the Northern Hemisphere and the first day of spring (vernal equinox) in the Southern Hemisphere.
(copyright: seasky.org)
* New Moon
   <2019-09-28 Sat 18:26>
September 28 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 18:26 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Draconids Meteor Shower
   <2019-10-08 Tue>
October 8 
The Draconids is a minor meteor shower producing only about 10 meteors per hour. It is produced by dust grains left behind by comet 21P Giacobini-Zinner, which was first discovered in 1900. The Draconids is an unusual shower in that the best viewing is in the early evening instead of early morning like most other showers. The shower runs annually from October 6-10 and peaks this year on the the night of the 8th. The first quarter moon will set shortly after midnight leaving fairly dark skies for observing. Best viewing will be in the early evening from a dark location far away from city lights. Meteors will radiate from the constellation Draco, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon
   <2019-10-13 Sun 21:09>
October 13 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 21:09 UTC. This full moon was known by early Native American tribes as the Full Hunters Moon because at this time of year the leaves are falling and the game is fat and ready to hunt. This moon has also been known as the Travel Moon and the Blood Moon.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2019-10-20 Sun>
October 20 
The planet Mercury reaches greatest eastern elongation of 24.6 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* Orionids Meteor Shower
   <2019-10-21 Mon>
October 21, 22 
The Orionids is an average shower producing up to 20 meteors per hour at its peak. It is produced by dust grains left behind by comet Halley, which has been known and observed since ancient times. The shower runs annually from October 2 to November 7. It peaks this year on the night of October 21 and the morning of October 22. The second quarter moon will block some of the fainter meteors this year, but the Orionids tend to be fairly bright so it could still be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Orion, but can appear anywhere in the sky.
(copyright: seasky.org)
* Uranus at Opposition
   <2019-10-27 Sun>
October 27 
The blue-green planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view Uranus. Due to its distance, it will only appear as a tiny blue-green dot in all but the most powerful telescopes.
(copyright: seasky.org)
* New Moon
   <2019-10-28 Mon 03:39>
October 28 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 03:39 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Taurids Meteor Shower
   <2019-11-05 Tue>
November 5, 6 
The Taurids is a long-running minor meteor shower producing only about 5-10 meteors per hour. It is unusual in that it consists of two separate streams. The first is produced by dust grains left behind by Asteroid 2004 TG10. The second stream is produced by debris left behind by Comet 2P Encke. The shower runs annually from September 7 to December 10. It peaks this year on the the night of November 5. The first quarter moon will set shortly after midnight leaving dark skies for viewing. Best viewing will be just after midnight from a dark location far away from city lights. Meteors will radiate from the constellation Taurus, but can appear anywhere in the sky.
(copyright: seasky.org)
* Rare Transit of Mercury Across the Sun
   <2019-11-11 Mon>
November 11 
The planet Mercury will move directly between the Earth and the Sun. Viewers with telescopes and approved solar filters will be able to observe the dark disk of the planet Mercury moving across the face of the Sun. This is an extremely rare event that occurs only once every few years. The next transit of Mercury will not take place until 2039. This transit will be visible throughout all of South America and Central America, and parts of North America, Mexico, Europe, the Middle East, and Africa. The best place to view this event in its entirety will be the eastern United States, Central America, and South America. (Transit Visibility Map and Information)
(copyright: seasky.org)
* Full Moon
   <2019-11-12 Tue 13:36>
November 12 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 13:36 UTC. This full moon was known by early Native American tribes as the Full Beaver Moon because this was the time of year to set the beaver traps before the swamps and rivers froze. It has also been known as the Frosty Moon and the Hunter's Moon.
(copyright: seasky.org)
* Leonids Meteor Shower
   <2019-11-17 Sun>
November 17, 18 
The Leonids is an average shower, producing up to 15 meteors per hour at its peak. This shower is unique in that it has a cyclonic peak about every 33 years where hundreds of meteors per hour can be seen. That last of these occurred in 2001. The Leonids is produced by dust grains left behind by comet Tempel-Tuttle, which was discovered in 1865. The shower runs annually from November 6-30. It peaks this year on the night of the 17th and morning of the 18th. The second quarter moon will block many of the fainter meteors this year, but if you are patient you should be able to catch quite a few of the brightest ones. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Leo, but can appear anywhere in the sky.
(copyright: seasky.org)
* Conjunction of Venus and Jupiter
   <2019-11-24 Sun>
November 24 
A conjunction of Venus and Jupiter will be visible on November 24. The two bright planets will be visible within 1.4 degrees of each other in the evening sky. Look for this impressive sight in the western sky just after sunset.
(copyright: seasky.org)
* New Moon
   <2019-11-26 Tue 15:06>
November 26 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 15:06 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2019-11-28 Thu>
November 28 
The planet Mercury reaches greatest western elongation of 20.1 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* Full Moon
   <2019-12-12 Thu 05:14>
December 12 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 05:14 UTC. This full moon was known by early Native American tribes as the Full Cold Moon because this is the time of year when the cold winter air settles in and the nights become long and dark. This moon has also been known as the Full Long Nights Moon and the Moon Before Yule.
(copyright: seasky.org)
* Geminids Meteor Shower
   <2019-12-13 Fri>
December 13, 14 
The Geminids is the  king of the meteor showers. It is considered by many to be the best shower in the heavens, producing up to 120 multicolored meteors per hour at its peak. It is produced by debris left behind by an asteroid known as 3200 Phaethon, which was discovered in 1982. The shower runs annually from December 7-17. It peaks this year on the night of the 13th and morning of the 14th. Unfortunately the nearly full moon will block out many of the meteors this year, but the Geminids are so bright and numerous that it could still be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Gemini, but can appear anywhere in the sky.
(copyright: seasky.org)
* December Solstice
   <2019-12-22 Sun 04:19>
December 22 
The December solstice occurs at 04:19 UTC. The South Pole of the earth will be tilted toward the Sun, which will have reached its southernmost position in the sky and will be directly over the Tropic of Capricorn at 23.44 degrees south latitude. This is the first day of winter (winter solstice) in the Northern Hemisphere and the first day of summer (summer solstice) in the Southern Hemisphere.
(copyright: seasky.org)
* Ursids Meteor Shower
   <2019-12-21 Sat>
December 21, 22 
The Ursids is a minor meteor shower producing about 5-10 meteors per hour. It is produced by dust grains left behind by comet Tuttle, which was first discovered in 1790. The shower runs annually from December 17 - 25. It peaks this year on the the night of the 21st and morning of the 22nd. The waning crescent moon should not  interfere too much this year. Skies should still be dark enough for what could be a good show. Best viewing will be just after midnight from a dark location far away from city lights. Meteors will radiate from the constellation Ursa Minor, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2019-12-26 Thu 05:15>
December 26 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 05:15 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
