* Quadrantids Meteor Shower
* Quadrantids Meteor Shower
   <2020-01-03 Fri>
January 3, 4 
The Quadrantids is an above average shower, with up to 40 meteors per hour at its peak. It is thought to be produced by dust grains left behind by an extinct comet known as 2003 EH1, which was discovered in 2003. The shower runs annually from January 1-5. It peaks this year on the night of the 3rd and  morning of the 4th. The first quarter moon will set shortly after midnight, leaving fairly dark skies for what could be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Bootes, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon
   <2020-01-10 Fri 19:23>
January 10 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 19:23 UTC. This full moon was known by early Native American tribes as the Full Wolf Moon because this was the time of year when hungry wolf packs howled outside their camps. This moon has also been know as the Old Moon and the Moon After Yule.
(copyright: seasky.org)
* Penumbral Lunar Eclipse
   <2020-01-10 Fri>
January 10 
A penumbral lunar eclipse occurs when the Moon passes through the Earth's partial shadow, or penumbra. During this type of eclipse the Moon will darken slightly but not completely. The eclipse will be visible throughout most of Europe, Africa, Asia, the Indian Ocean, and Western Australia. (NASA Map and Eclipse Information)
(copyright: seasky.org)
* New Moon
   <2020-01-24 Fri 21:44>
January 24 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 21:44 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2020-02-09 Sun 07:34>
February 9 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 07:34 UTC. This full moon was known by early Native American tribes as the Full Snow Moon because the heaviest snows usually fell during this time of the year. Since hunting is difficult, this moon has also been known by some tribes as the Full Hunger Moon, since the harsh weather made hunting difficult. This is also the first of four supermoons for 2020. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2020-02-10 Mon>
February 10 
The planet Mercury reaches greatest eastern elongation of 18.2 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* New Moon
   <2020-02-23 Sun 15:33>
February 23 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 15:33 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2020-03-09 Mon 17:48>
March 9 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 17:48 UTC. This full moon was known by early Native American tribes as the Full Worm Moon because this was the time of year when the ground would begin to soften and the earthworms would reappear. This moon has also been known as the Full Crow Moon, the Full Crust Moon, the Full Sap Moon, and the Lenten Moon. This is also the second of four supermoons for 2020. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* March Equinox
   <2020-03-20 Fri 03:50>
March 20 
The March equinox occurs at 03:50 UTC. The Sun will shine directly on the equator and there will be nearly equal amounts of day and night throughout the world. This is also the first day of spring (vernal equinox) in the Northern Hemisphere and the first day of fall (autumnal equinox) in the Southern Hemisphere.
(copyright: seasky.org)
* New Moon
   <2020-03-24 Tue 09:29>
March 24 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 09:29 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2020-03-24 Tue>
March 24 
The planet Mercury reaches greatest western elongation of 27.8 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* Venus at Greatest Eastern Elongation
   <2020-03-24 Tue>
March 24 
The planet Venus reaches greatest eastern elongation of 46.1 degrees from the Sun. This is the best time to view Venus since it will be at its highest point above the horizon in the evening sky. Look for the bright planet in the western sky after sunset.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2020-04-08 Wed 02:35>
April 8 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 02:35 UTC. This full moon was known by early Native American tribes as the Full Pink Moon because it marked the appearance of the moss pink, or wild ground phlox, which is one of the first spring flowers. This moon has also been known as the Sprouting Grass Moon, the Growing Moon, and the Egg Moon. Many coastal tribes called it the Full Fish Moon because this was the time that the shad swam upstream to spawn. This is also the third of four supermoons for 2020. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* Lyrids Meteor Shower
   <2020-04-22 Wed>
April 22, 23 
The Lyrids is an average shower, usually producing about 20 meteors per hour at its peak. It is produced by dust particles left behind by comet C/1861 G1 Thatcher, which was discovered in 1861. The shower runs annually from April 16-25. It peaks this year on the night of the night of the 22nd and morning of the 23rd. These meteors can sometimes produce bright dust trails that last for several seconds.  The nearly new moon will ensure dark skies for what should be a good show this year. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Lyra, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2020-04-23 Thu 02:27>
April 23 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 02:27 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Eta Aquarids Meteor Shower
   <2020-05-06 Wed>
May 6, 7 
The Eta Aquarids is an above average shower, capable of producing up to 60 meteors per hour at its peak. Most of the activity is seen in the Southern Hemisphere. In the Northern Hemisphere, the rate can reach about 30 meteors per hour. It is produced by dust particles left behind by comet Halley, which has known and observed since ancient times. The shower runs annually from April 19 to May 28. It peaks this year on the night of May 6 and the morning of the May 7. The nearly full moon will be a problem this year, blocking out all but the brightest meteors. But if you are patient, you should still should be able to catch a few good ones. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Aquarius, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon, Supermoon
   <2020-05-07 Thu 10:45>
May 7 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 10:45 UTC. This full moon was known by early Native American tribes as the Full Flower Moon because this was the time of year when spring flowers appeared in abundance. This moon has also been known as the Full Corn Planting Moon and the Milk Moon. This is also the last of four supermoons for 2020. The Moon will be at its closest approach to the Earth and may look slightly larger and brighter than usual.
(copyright: seasky.org)
* New Moon
   <2020-05-22 Fri 17:39>
May 22 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 17:39 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2020-06-04 Thu>
June 4 
The planet Mercury reaches greatest eastern elongation of 23.6 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* Full Moon
   <2020-06-05 Fri 19:12>
June 5 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 19:12 UTC. This full moon was known by early Native American tribes as the Full Strawberry Moon because it signaled the time of year to gather ripening fruit. It also coincides with the peak of the strawberry harvesting season. This moon has also been known as the Full Rose Moon and the Full Honey Moon.
(copyright: seasky.org)
* Penumbral Lunar Eclipse
   <2020-06-05 Fri>
June 5 
A penumbral lunar eclipse occurs when the Moon passes through the Earth's partial shadow, or penumbra. During this type of eclipse the Moon will darken slightly but not completely. The eclipse will be visible throughout most of Europe, Africa, Asia, Australia, the Indian Ocean, and Australia. 
      (NASA Map and Eclipse Information)
(copyright: seasky.org)
* New Moon
   <2020-06-21 Sun 06:42>
June 21 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 06:42 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Annular Solar Eclipse
   <2020-06-21 Sun>
June 21 
 An annular solar eclipse occurs when the Moon is too far away from the Earth to completely cover the Sun. This results in a ring of light around the darkened Moon. The Sun's corona is not visible during an annular eclipse. The path of the eclipse will begin in central Africa and travel through Saudi Arabia, northern India, and southern China before ending in the Pacific Ocean. A partial eclipse will be visible throughout most of eastern Africa, the Middle East, and southern Asia. (NASA Map and Eclipse Information) (NASA Interactive Google Map)
(copyright: seasky.org)
* June Solstice
   <2020-06-22 Mon 21:44>
June 22 
The June solstice occurs at 21:44 UTC. The North Pole of the earth will be tilted toward the Sun, which will have reached its northernmost position in the sky and will be directly over the Tropic of Cancer at 23.44 degrees north latitude. This is the first day of summer (summer solstice) in the Northern Hemisphere and the first day of winter (winter solstice) in the Southern Hemisphere.
(copyright: seasky.org)
* Full Moon
   <2020-07-05 Sun 04:44>
July 5 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 04:44 UTC. This full moon was known by early Native American tribes as the Full Buck Moon because the male buck deer would begin to grow their new antlers at this time of year. This moon has also been known as the Full Thunder Moon and the Full Hay Moon.
(copyright: seasky.org)
* Penumbral Lunar Eclipse
   <2020-07-05 Sun>
July 5 
A penumbral lunar eclipse occurs when the Moon passes through the Earth's partial shadow, or penumbra. During this type of eclipse the Moon will darken slightly but not completely. The eclipse will be visible throughout most of North America, South America, the eastern Pacific Ocean, the western Atlantic Ocean, and extreme western Africa. (NASA Map and Eclipse Information)
(copyright: seasky.org)
* Jupiter at Opposition
   <2020-07-14 Tue>
July 14 
The giant planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Jupiter and its moons. A medium-sized telescope should be able to show you some of the details in Jupiter's cloud bands. A good pair of binoculars should allow you to see Jupiter's four largest moons, appearing as bright dots on either side of the planet. 
(copyright: seasky.org)
* New Moon
   <2020-07-20 Mon 17:33>
July 20 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 17:33 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Saturn at Opposition
   <2020-07-20 Mon>
July 20 
The ringed planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Saturn and its moons. A medium-sized or larger telescope will allow you to see Saturn's rings and a few of its brightest moons.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2020-07-22 Wed>
July 22 
The planet Mercury reaches greatest western elongation of 20.1 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* Delta Aquarids Meteor Shower
   <2020-07-28 Tue>
July 28, 29 
The Delta Aquarids is an average shower that can produce up to 20 meteors per hour at its peak. It is produced by debris left behind by comets Marsden and Kracht. The shower runs annually from July 12 to August 23. It peaks this year on the night of July 28 and morning of July 29. The second quarter moon will block many of the fainter meteors this year. But if you are patient, you should still be able to catch a few of the brighter ones. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Aquarius, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon
   <2020-08-03 Mon 15:59>
August 3 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 15:59 UTC. This full moon was known by early Native American tribes as the Full Sturgeon Moon because the large sturgeon fish of the Great Lakes and other major lakes were more easily caught at this time of year. This moon has also been known as the Green Corn Moon and the Grain Moon.
(copyright: seasky.org)
* Perseids Meteor Shower
   <2020-08-12 Wed>
August 12, 13 
The Perseids is one of the best meteor showers to observe, producing up to 60 meteors per hour at its peak. It is produced by comet Swift-Tuttle, which was discovered in 1862. The Perseids are famous for producing a large number of bright meteors. The shower runs annually from July 17 to August 24. It peaks this year on the night of August 12 and the morning of August 13. The second quarter moon will block out some of the fainter meteors this year, but the Perseids are so bright and numerous that it should still be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Perseus, but can appear anywhere in the sky.
(copyright: seasky.org)
* Venus at Greatest Western Elongation
   <2020-08-13 Thu>
August 13 
The planet Venus reaches greatest eastern elongation of 45.8 degrees from the Sun. This is the best time to view Venus since it will be at its highest point above the horizon in the morning sky. Look for the bright planet in the eastern sky before sunrise.
(copyright: seasky.org)
* New Moon
   <2020-08-19 Wed 02:42>
August 19 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 02:42 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Full Moon
   <2020-09-02 Wed 05:23>
September 2 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 05:23 UTC. This full moon was known by early Native American tribes as the Full Corn Moon because the corn is harvested around this time of year.
(copyright: seasky.org)
* Neptune at Opposition
   <2020-09-11 Fri>
September 11 
The blue giant planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Neptune. Due to its extreme distance from Earth, it will only appear as a tiny blue dot in all but the most powerful telescopes.
(copyright: seasky.org)
* New Moon
   <2020-09-17 Thu 11:00>
September 17 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 11:00 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* September Equinox
   <2020-09-22 Tue 13:31>
September 22 
The September equinox occurs at 13:31 UTC. The Sun will shine directly on the equator and there will be nearly equal amounts of day and night throughout the world. This is also the first day of fall (autumnal equinox) in the Northern Hemisphere and the first day of spring (vernal equinox) in the Southern Hemisphere.
(copyright: seasky.org)
* Full Moon
   <2020-10-01 Thu 21:06>
October 1 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 21:06 UTC. This full moon was known by early Native American tribes as the Full Hunters Moon because at this time of year the leaves are falling and the game is fat and ready to hunt. This moon has also been known as the Travel Moon and the Blood Moon. This moon is also known as the Harvest Moon. The Harvest Moon is the full moon that occurs closest to the September equinox each year.
(copyright: seasky.org)
* Mercury at Greatest Eastern Elongation
   <2020-10-01 Thu>
October 1 
The planet Mercury reaches greatest eastern elongation of 25.8 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the evening sky. Look for the planet low in the western sky just after sunset.
(copyright: seasky.org)
* Draconids Meteor Shower
   <2020-10-07 Wed>
October 7 
The Draconids is a minor meteor shower producing only about 10 meteors per hour. It is produced by dust grains left behind by comet 21P Giacobini-Zinner, which was first discovered in 1900. The Draconids is an unusual shower in that the best viewing is in the early evening instead of early morning like most other showers. The shower runs annually from October 6-10 and peaks this year on the the night of the 7th. The second quarter moon will ensure dark skies in the early evening for what should be a good show. Best viewing will be in the early evening from a dark location far away from city lights. Meteors will radiate from the constellation Draco, but can appear anywhere in the sky.
(copyright: seasky.org)
* Mars at Opposition
   <2020-10-13 Tue>
October 13 
The red planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view and photograph Mars. A medium-sized telescope will allow you to see some of the dark details on the planet's orange surface.
(copyright: seasky.org)
* New Moon
   <2020-10-16 Fri 19:32>
October 16 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 19:32 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Orionids Meteor Shower
   <2020-10-21 Wed>
October 21, 22 
The Orionids is an average shower producing up to 20 meteors per hour at its peak. It is produced by dust grains left behind by comet Halley, which has been known and observed since ancient times. The shower runs annually from October 2 to November 7. It peaks this year on the night of October 21 and the morning of October 22. The waxing crescent moon will set before midnight leaving dark skies for what should be a good show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Orion, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon, Blue Moon
   <2020-10-31 Sat 14:51>
October 31 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 14:51 UTC. Since this is the second full moon in the same month, it is sometimes referred to as a blue moon. This rare calendar event only occurs every few months, giving rise to the term "once in a blue moon".
(copyright: seasky.org)
* Uranus at Opposition
   <2020-10-31 Sat>
October 31 
The blue-green planet will be at its closest approach to Earth and its face will be fully illuminated by the Sun. It will be brighter than any other time of the year and will be visible all night long. This is the best time to view Uranus. Due to its distance, it will only appear as a tiny blue-green dot in all but the most powerful telescopes.
(copyright: seasky.org)
* Taurids Meteor Shower
   <2020-11-04 Wed>
November 4, 5 
The Taurids is a long-running minor meteor shower producing only about 5-10 meteors per hour. It is unusual in that it consists of two separate streams. The first is produced by dust grains left behind by Asteroid 2004 TG10. The second stream is produced by debris left behind by Comet 2P Encke. The shower runs annually from September 7 to December 10. It peaks this year on the the night of November 4. The first quarter moon will block out all but the brightest meteors this year. If you are patient, you may still be able to catch a few good ones. Best viewing will be just after midnight from a dark location far away from city lights. Meteors will radiate from the constellation Taurus, but can appear anywhere in the sky.
(copyright: seasky.org)
* Mercury at Greatest Western Elongation
   <2020-11-10 Tue>
November 10 
The planet Mercury reaches greatest western elongation of 19.1 degrees from the Sun. This is the best time to view Mercury since it will be at its highest point above the horizon in the morning sky. Look for the planet low in the eastern sky just before sunrise.
(copyright: seasky.org)
* New Moon
   <2020-11-15 Sun 05:08>
November 15 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 05:08 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Leonids Meteor Shower
   <2020-11-17 Tue>
November 17, 18 
The Leonids is an average shower, producing up to 15 meteors per hour at its peak. This shower is unique in that it has a cyclonic peak about every 33 years where hundreds of meteors per hour can be seen. That last of these occurred in 2001. The Leonids is produced by dust grains left behind by comet Tempel-Tuttle, which was discovered in 1865. The shower runs annually from November 6-30. It peaks this year on the night of the 17th and morning of the 18th. The crescent moon will set early in the evening leaving dark skies for what should be an excellent show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Leo, but can appear anywhere in the sky.
(copyright: seasky.org)
* Full Moon
   <2020-11-30 Mon 09:32>
November 30 
The Moon will be located on the opposite side of the Earth as the Sun and its face will be will be fully illuminated. This phase occurs at 09:32 UTC. This full moon was known by early Native American tribes as the Full Beaver Moon because this was the time of year to set the beaver traps before the swamps and rivers froze. It has also been known as the Frosty Moon and the Hunter's Moon.
(copyright: seasky.org)
* Penumbral Lunar Eclipse
   <2020-11-30 Mon>
November 30 
A penumbral lunar eclipse occurs when the Moon passes through the Earth's partial shadow, or penumbra. During this type of eclipse the Moon will darken slightly but not completely. The eclipse will be visible throughout most of North America, the Pacific Ocean, and northeastern Asia including Japan. (NASA Map and Eclipse Information)
(copyright: seasky.org)
* Geminids Meteor Shower
   <2020-12-13 Sun>
December 13, 14 
The Geminids is the  king of the meteor showers. It is considered by many to be the best shower in the heavens, producing up to 120 multicolored meteors per hour at its peak. It is produced by debris left behind by an asteroid known as 3200 Phaethon, which was discovered in 1982. The shower runs annually from December 7-17. It peaks this year on the night of the 13th and morning of the 14th. The morning of the 15th could also be nearly as active this year. The nearly new moon will ensure dark skies for what should be an excellent show. Best viewing will be from a dark location after midnight. Meteors will radiate from the constellation Gemini, but can appear anywhere in the sky.
(copyright: seasky.org)
* New Moon
   <2020-12-14 Mon 16:18>
December 14 
The Moon will located on the same side of the Earth as the Sun and will not be visible in the night sky. This phase occurs at 16:18 UTC. This is the best time of the month to observe faint objects such as galaxies and star clusters because there is no moonlight to interfere.
(copyright: seasky.org)
* Total Solar Eclipse
   <2020-12-14 Mon>
December 14 
A total solar eclipse occurs when the moon completely blocks the Sun, revealing the Sun's beautiful outer atmosphere known as the corona. The path of totality will only be visible in parts of southern Chile and southern Argentina. A partial eclipse will be visible in most parts of southern South America, the southeastern Pacific Ocean and the southern Atlantic Ocean.
        (NASA Map and Eclipse Information) (NASA Interactive Google Map)
(copyright: seasky.org)
* December Solstice
   <2020-12-21 Mon 10:02>
December 21 
The December solstice occurs at 10:02 UTC. The South Pole of the earth will be tilted toward the Sun, which will have reached its southernmost position in the sky and will be directly over the Tropic of Capricorn at 23.44 degrees south latitude. This is the first day of winter (winter solstice) in the Northern Hemisphere and the first day of summer (summer solstice) in the Southern Hemisphere.
(copyright: seasky.org)
* Rare Conjunction of Jupiter and Saturn
   <2020-12-21 Mon>
December 21 
A conjunction of Jupiter and Saturn will take place on December 21. This rare conjunction of these two planets is known as a great conjunction. The last great conjunction occurred in the year 2000. The two bright planets will appear only 7 arc minutes of each other in the night sky. They will be so close that they will appear to make a bright double planet. Look to the west just after sunset for this impressive and rare planetary pair.
(copyright: seasky.org)
* Ursids Meteor Shower
   <2020-12-21 Mon>
December 21, 22 
The Ursids is a minor meteor shower producing about 5-10 meteors per hour. It is produced by dust grains left behind by comet Tuttle, which was first discovered in 1790. The shower runs annually from December 17-25. It peaks this year on the the night of the 21st and morning of the 22nd. The first quarter moon should set just after midnight leaving dark skies for what could be a good show. Best viewing will be just after midnight from a dark location far away from city lights. Meteors will radiate from the constellation Ursa Minor, but can appear anywhere in the sky.
(copyright: seasky.org)
